server:
  servlet:
    context-path: /market

spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emm?useSSL=false&serverTimezone=GMT%2b8
      username: root
      password: 1234
  servlet:
    multipart:
      max-file-size: 10mb

storage:
  location: D:/ei-market-master/market-front/src/assets/
  source: D:/ei-market-master/pic/img/%s.jpg